name: healthcare-fair-workflow
channels:
  - conda-forge

dependencies:
  - python=3.11.9
  - pandas=2.2.2
  - numpy=1.26.4
  - matplotlib=3.8.4
  - seaborn=0.13.2
  - scikit-learn=1.4.2
  - scipy=1.13.1
  - jupyterlab=4.2.5


  